
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   DeBounce
// DESIGN:   DeBounce
// FILENAME: DeBounce_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ns / 100 ps

// Define Module for Test Fixture
module DeBounce_tf();

// Inputs
    reg clk;
    reg rst;
    reg btn_in;


// Outputs
    wire db_out;




// Instantiate the DUT
    DeBounce DUT (
        .clk(clk), 
        .rst(rst), 
        .btn_in(btn_in), 
        .db_out(db_out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
      
          //This is needed to have everything plotted
    	$dumpfile("dump.vcd");
    	$dumpvars;
    
			$display ($time, " << Starting the Simulation >> ");
            clk = 1'b0;
            rst = 1'b0;
			#200 rst = 1'b1;      // at time 200 release the reset
            btn_in = 1'b0;
    end


	always 
			#10 clk = ~clk;    // every ten nanoseconds invert the clock

	always 
		begin
			#40000 btn_in = 1'b1;
			
			#400 btn_in = 1'b0;		
			
			#800 btn_in = 1'b1;	
			
			#800 btn_in = 1'b0;				
			
			#800 btn_in = 1'b1;

			#40000 btn_in = 1'b0;
			
			#4000 btn_in = 1'b1;		
			
			#40000 btn_in = 1'b0;

			#400 btn_in = 1'b1;
			
			#800 btn_in = 1'b0;		
			
			#800 btn_in = 1'b1;

			#800 btn_in = 1'b0;
			
			#40000 btn_in = 1'b1;		
			
			#4000 btn_in = 1'b0;

		end


     // This parallel process determines the length of the simulation
     initial //Simulation is run for 800ns
     #310000  $finish; 


endmodule // DeBounce_tf