flowchart TD

    subgraph UART["UART"]
        REG["Registro"]
    end

    subgraph FPGA["FPGA"]

        TOPO["Show_mole"]
        PRESS["Press_btn"]
        FSM["FSM<br/>Máquina de Estados"]
        STATE["Estado de juego"]
        

            subgraph TIME["Time_Logic"]

            end
        
            subgraph CA["Contador Acierto"<br/>Hit_Counter]
                DECO_BSD["Deco BSD"]
                SUM["Sumador"]


            end
        
            subgraph C_F["Contador Fallo"<br/>Fail_Counter]
                DE_BSD["Deco BSD"]
                SUM_F["Sumador"]
                CONT["Contador"]
            end

            subgraph UART_R["Receptor UART"]
                CON_U
                REG_U["REG UART"]
                CLK_U

                CLK_U -->|"9600 Hz"| REG_U
                CLK_U --> CON_U
                REG_U -->|"dato [7:0]"| CON_U
                CON_U -->|"en"| REG_U

            end
        
            



        CLK--> FSM
        rst--> FSM
        FSM -->|"pos_topo [7:0]"| TOPO
        PRESS -->|"btn [7:0]"| FSM
        FSM -->|"hit"| TIME
        FSM -->|"estado [1:0]"| STATE
        FSM -->|"acierto [6:0]"| CA
        FSM -->|"fallo [1:0]"| C_F
        REG_U -->|"pos_topo [2:0]"| FSM  
        TIME -->|"UP"| FSM
        FSM -->|"sol"| REG

    end
    REG -->|"pos(8)"| REG_U
    BTN["Botones"]

    
    LED8["LED's Topos"]
    LED["LED estado"]
    MARK["Marcador"]
    
    TOPO -->|"pos_topo [7:0]"| LED8
    STATE -->|"estado"| LED
    CA -->|"acierto [6:0]"| MARK
    C_F -->|"fallo [1:0]"| MARK
    BTN -->|"btn [7:0]"| PRESS


    