flowchart LR
subgraph UART["UART"]

    S1["FF"] --> S2["FF"]
    S2["FF"] --> SYNC["pos(8)_sync"]
    
    SYNC --> FEDGE
    SYNC --> EDGE["Detector de flanco<br/>(AND)"]
    FEDGE --> EDGE
    EDGE -->|"start_bit"| CTRL["FSM de control<br/>(2 FF + lógica)"]
    CTRL -->|"estado"| MUX["Mux 2:1<br/>umbral"]
    MUX -->|"N/2-1 o N-1"| TCNT["Contador de tiempo<br/>descendente, con carga"]
    CTRL -->|"load"| TCNT
    TCNT --> CMP0["Comparador = 0"]
    CMP0 -->|"flag_cont"| CTRL
    CTRL -->|"shift_en"| SH["Registro de<br/>desplazamiento 8 bits"]
    SYNC --> SH
    SH --> BCNT["Contador de bits<br/>ascendente 0-7"]
    CTRL -->|"shift_en"| BCNT
    BCNT --> CMP8["Comparador = 8"]
    CMP8 -->|"cont_8"| CTRL
    SYNC --> CTRL
    CTRL -->|"valid_pos"| VAL["valid_pos"]
    VAL --> AND1["AND captura"]
    
    SH -->|"dato[2:0]"| REGOUT["Registro de salida<br/>pos_topo[2:0]"]
    AND1 -->|captura| REGOUT


end
    pos["pos(8)"] --> S1["FF"]

    CLK["clk 100MHz"] --> S1
    CLK --> S2
    CLK --> FEDGE["FF pos_sync_prev"]
    
    en_save_pos["en_save_pos"] --> AND1
    REGOUT --> pos_topo["pos_topo[2:0]"]

    rst["rst"] --> S1
    rst --> S2
    rst --> FEDGE
    rst --> CTRL
    rst --> TCNT
    rst --> SH
    rst --> BCNT
    rst --> REGOUT